micronaut:
  application:
    name: authorService
  server:
    port: 7000

sentry:
  dns: ${SENTRY_DNS:`SENTRY_DNS_VALUE`}
  environment: ${SENTRY_ENV:debug}

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    schema-generate: CREATE_DROP

jpa:
  default:
    entity-scan:
      packages: 'org.wcode.author.service.domain.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
